module_name         = "ROOT"
uuid                = "1706fdcc-8426-44f1-a283-5be479e9517c"
version             = "0.4.0"

export_jl_fname     = "ROOT-export.jl"
module_jl_fname     = "ROOT-generated.jl"
lib_basename        = "$(@__DIR__)/../deps/libroot_julia"
out_cxx_dir         = "ROOT/deps/src"

include_dirs        = [ "/home/pgras/.julia/artifacts/541477a5cefd778e4ecbd314cfbc99eed20f2c4c/include", "src", "/home/pgras/.julia/artifacts/18df5e18057f7c98339fdbbc02a6da42d38b237e/include", "/usr/include/c++/12" ]

input               = [
   # Base package (core/base) >>>
   # "Bswapcpy.h", not relevant
   "Buttons.h", "Bytes.h", "Byteswap.h", "GLConstants.h", "Gtypes.h", "Htypes.h",
   "KeySymbols.h", "Match.h", "MessageTypes.h", "RConfig.h", "Riostream.h", "Rpair.h",
   "RQ_OBJECT.h", "RStipples.h", "Rtypes.h", "Strlen.h", "TApplication.h", "TAtt3D.h",
   "TAttAxis.h", "TAttBBox2D.h", "TAttBBox.h", "TAttFill.h", "TAttLine.h", "TAttMarker.h",
   "TAttPad.h", "TAttText.h", "TBase64.h", "TBenchmark.h", "TBuffer3D.h", "TBuffer3DTypes.h",
   "TBuffer.h", "TColorGradient.h", "TColor.h", "TDatime.h", "TDirectory.h", "TEnv.h",
   "TException.h", "TExec.h", "TFileCollection.h", "TFileInfo.h", "TFolder.h", "TInetAddress.h",
   "TMacro.h", 
   "TMathBase.h", # causing duplicate error
   "TMD5.h",
   #"TMemberInspector.h", fail, but not required
   "TMessageHandler.h", "TNamed.h", "TNotifyLink.h", "TObject.h",
   #"TObjString.h", fails
   "TParameter.h", "TPluginManager.h", "TPoint.h", "TPRegexp.h", "TProcessID.h",
   "TProcessUUID.h", "TQClass.h", "TQCommand.h", "TQConnection.h", "TQObject.h",
   "TRedirectOutputGuard.h",
    #"TRefCnt.h", causes a duplicate error, removed as we expect TRefCnt is used internally only
   "TRef.h", "TRegexp.h", "TRemoteObject.h", "TROOT.h", "TRootIOCtor.h", "TStopwatch.h",
   #"TStorage.h", fails, but no required
   "TString.h",
   #"TStringLong.h", deprecated
   "TStyle.h",
   #"TSysEvtHandler.h",
   "TSystemDirectory.h", "TSystemFile.h", "TSystem.h", "TTask.h", "TThreadSlots.h", "TTime.h",
   "TTimer.h", "TTimeStamp.h", "TUri.h", "TUrl.h", "TUUID.h", "TVersionCheck.h", "TVirtualAuth.h",
   "TVirtualFFT.h",
   #"TVirtualGL.h",
   "TVirtualMapFile.h", "TVirtualMonitoring.h", "TVirtualMutex.h", "TVirtualPadEditor.h",
   "TVirtualPad.h", "TVirtualPadPainter.h", "TVirtualPerfStats.h", "TVirtualPS.h", "TVirtualQConnection.h",
   "TVirtualRWMutex.h", "TVirtualTableInterface.h", "TVirtualViewer3D.h", "TVirtualX.h",
   #"Varargs.h", contains only #define's
   "ROOT/EExecutionPolicy.hxx", "ROOT/RFloat16.hxx", "ROOT/StringConv.hxx", "ROOT/TErrorDefaultHandler.hxx",
   "ROOT/TExecutorCRTP.hxx", "ROOT/TSequentialExecutor.hxx",
   # <<< Base package

   # Containers package >>>
   "TCollection.h", "TBits.h", "TClassTable.h", "TArrayL.h", "TBtree.h", "TArrayD.h",
   "TCollectionProxyInfo.h", "TArrayF.h", "TRefArray.h", "TRefTable.h", "TArrayC.h",
   "TArray.h", "TExMap.h", "THashTable.h", "TArrayS.h", "THashList.h", "TObjArray.h",
   "TVirtualCollectionProxy.h", "TMap.h", "TOrdCollection.h", "TArrayL64.h", "TSortedList.h",
   "TIterator.h", "TArrayI.h", "TClonesArray.h", "ROOT/TSeq.hxx", 
   "TList.h",
   "TSeqCollection.h", "TObjectTable.h",
   # <<< Containers package

  "TBrowser.h", "TTree.h", "TBranchPtr.h",
  "TLeaf.h", "TLeafB.h", "TLeafC.h", "TLeafD32.h", "TLeafD.h", "TLeafElement.h", "TLeafF16.h",
  "TLeafF.h", "TLeafG.h", "TLeafI.h", "TLeafL.h", "TLeafObject.h", "TLeafO.h", "TLeafS.h", 
  "TBranch.h", "TBranchObject.h", "TBranchElement.h", "TBranchSTL.h",
  "TTreeReader.h", "TTreeReaderValue.h", "TTreeReaderArray.h",
  "TCanvas.h", "TRandom.h", "TRandom.h", "TDirectoryFile.h", "TFile.h",
  "TEntryList.h", "TKey.h", "TObjArray.h", "TVectorT.h", "TVectorDfwd.h", "TVectorFfwd.h",
  "Templates.h",  "Extra.h",

   #
   # Histogram package (hist/hist/inc/) >>>
  "Foption.h", "HFitInterface.h", "TAxis.h", "TAxisModLab.h",
  "TBackCompFitter.h", "TBinomialEfficiencyFitter.h", "TConfidenceLevel.h",
  "TEfficiency.h", "TF12.h", "TF1AbsComposition.h", "TF1Convolution.h", "TF1.h",
  "TF1NormSum.h", "TF2.h", "TF3.h", "TFitResult.h", "TFitResultPtr.h",
  "TFormula.h", "TFractionFitter.h", "TGraph2DAsymmErrors.h",
  "TGraph2DErrors.h", "TGraph2D.h", "TGraphAsymmErrors.h", "TGraphBentErrors.h",
  "TGraphDelaunay2D.h", "TGraphDelaunay.h", "TGraphErrors.h", "TGraph.h",
  "TGraphMultiErrors.h", "TGraphSmooth.h", "TGraphTime.h", "TH1C.h", "TH1D.h",
  "TH1F.h", "TH1.h", "TH1I.h", "TH1K.h", "TH1S.h", "TH2C.h", "TH2D.h", "TH2F.h",
  "TH2.h", "TH2I.h", "TH2Poly.h", "TH2S.h", "TH3C.h", "TH3D.h", "TH3F.h",
  "TH3.h", "TH3I.h", "TH3S.h", "THistRange.h", "THLimitsFinder.h", "THnBase.h",
  "THnChain.h", "THn.h", "THnSparse.h", "THStack.h",
  "TKDE.h", "TLimitDataSource.h", "TLimit.h", "TMultiDimFit.h", #"TMultiGraph.h",
  "TNDArray.h", "TPolyMarker.h", "TPrincipal.h", "TProfile2D.h",
  "TProfile2Poly.h", "TProfile3D.h", "TProfile.h", "TScatter.h", "TSpline.h",
  "TSVDUnfold.h", "TVirtualFitter.h", "TVirtualGraphPainter.h",
  "TVirtualHistPainter.h", "TVirtualPaveStats.h",
   # <<< Histogram package
   #
   # Geometry package (geom/geom/inc/) >>>
   "TGDMLMatrix.h", "TGeant4PhysicalConstants.h", "TGeant4SystemOfUnits.h",
   "TGeoArb8.h", "TGeoAtt.h", "TGeoBBox.h", "TGeoBoolNode.h",
   "TGeoBranchArray.h", "TGeoBuilder.h", "TGeoCache.h", "TGeoCompositeShape.h",
   "TGeoCone.h", "TGeoElement.h", "TGeoEltu.h", "TGeoExtension.h",
   "TGeoGlobalMagField.h", "TGeoHalfSpace.h", "TGeoHelix.h", "TGeoHype.h",
   "TGeoManager.h", "TGeoMaterial.h", "TGeoMatrix.h", "TGeoMedium.h",
   "TGeoNavigator.h", "TGeoNode.h", "TGeoOpticalSurface.h", "TGeoParaboloid.h",
   "TGeoPara.h", "TGeoParallelWorld.h", "TGeoPatternFinder.h", "TGeoPcon.h",
   "TGeoPgon.h", "TGeoPhysicalConstants.h", "TGeoPhysicalNode.h",
   "TGeoPolygon.h", "TGeoRCPtr.h", "TGeoRegion.h", "TGeoScaledShape.h",
   "TGeoShapeAssembly.h", "TGeoShape.h", "TGeoSphere.h", "TGeoStateInfo.h",
   "TGeoSystemOfUnits.h", "TGeoTessellated.h", "TGeoTorus.h", "TGeoTrd1.h",
   "TGeoTrd2.h", "TGeoTube.h", "TGeoTypedefs.h", "TGeoUniformMagField.h",
   "TGeoVector3.h", "TGeoVolume.h", "TGeoVoxelFinder.h", "TGeoXtru.h",
   "TVirtualGeoConverter.h", "TVirtualGeoPainter.h", "TVirtualGeoTrack.h",
   "TVirtualMagField.h",
   # <<< Geometry package
   ]

class_order_constraints = [ "TTreeReader < TTreeReaderValue" ]

extra_headers       = [ "TVectorT.h", "cstdint" ]

veto_list           = "src/jlROOT-veto.h"

julia_names         = [ "TDirectoryFile::Get -> Get_",
                        "TDirectory::Get -> Get_",
                        "begin -> thebegin",
                        "start -> thestart",
                        "end -> theend",
                        "TSubString::String -> GetString",
                        "TString::SubString -> GetSubString",
                        "TRandom::Integer -> GetInteger",
                        "TBuffer3D::Type -> GetType",
                        "TVirtualPS::Text -> GetText",
                        "TGeoManager::Matrix -> GetMatrix",
                        "TGeoBuilder::Matrix -> GetMatrix",
                        "TROOT::Timer -> GetTimer"
]

fields_and_variables = true

# Currently not working with CxxWrap 0.15+, use 0.14.x
cxxwrap_version = "0.17"

#auto_veto           = false

vetoed_copy_ctor_classes = [ "TTreeReader", "RDataFrame" ]

#cxx-std             = "c++20"
cxx-std             = "c++17"

inheritances        = [ "TROOT:" ]

export_blacklist    = [ "String", "Integer", "Set", "Timer", "cd", "mkdir", "pwd", "begin", "end" ]

n_classes_per_file  = 5
#n_classes_per_file  = -1

# TGeoVolume, TGeoShape and TGeoMedium instances are deleted by the TGeoManager
# (see https://root.cern/doc/master/classTGeoVolume.html)
vetoed_finalizer_classes = [ "TTree", "TGeoVolume", "TGeoShape", "TGeoMedium", "TGeoMaterial", "TGeoManager" ]

#FIMXE do direct mapping when it is relevant to use a special names for the type also in Julia
#      that is for Stat_t, Font_t, Style_t, Marker_t, and Color_t
cxx2cxx_type_map = ["UChar_t      -> uint8_t",    #Unsigned Character 1 byte (unsigned char)
                    "Char_t       -> char"  ,     #Signed Character 1 byte (char)
                    "UShort_t     -> uint16_t",   #Unsigned Short integer 2 bytes (unsigned short)
                    "Short_t      -> int16_t",    #Signed Short integer 2 bytes (short)
                    "UInt_t       -> uint32_t",   #Unsigned int,eger 4 bytes
                    "Int_t        -> int32_t",    #Signed integer 4 bytes
                    "Seek_t       -> int",        #File pointer (int)
                    "ULong_t      -> uint64_t",   #Unsigned long integer 8 bytes (unsigned long)
                    "Long_t       -> int64_t",    #Signed long integer 8 bytes (long)
                    "Float_t      -> float",      #Float 4 bytes (float)
                    "Double_t     -> double",     #Double 8 bytes
                    "Text_t *     -> (const char *, std::string)",  #General string (char)
                    "Bool_t       -> bool",       #Boolean (0=false, 1=true) (bool)
                    "Byte_t       -> uint8_t",    #Byte (8 bits) (unsigned char)
                    "Version_t    -> int16_t",    #Class version identifier (short)
                    "const Option_t * -> (const char *, std::string)", #Option string (const char)
                    "Option_t *   -> (const char *, std::string)", #Option string (const char)
                    "Ssiz_t       -> int",        #String size (int)
                    "Real_t       -> float",      #TVector and TMatrix element type (float)
                    "ULong64_t    -> uint64_t",   #Portable unsigned long integer 8 bytes
                    "Long64_t     -> int64_t",    #Portable signed long integer 8 bytes
                    "ULongptr_t   -> uint64_t",   #Unsigned integer large enough to hold a pointer
                    "Longptr_t    -> int64_t",    #Integer large enough to hold a pointer
                    "Axis_t       -> double",     #Axis values type (double)
                    "Stat_t       -> double",     #Statistics type (double)
                    "Font_t       -> int16_t",    #Font number (short)
                    "Style_t      -> int16_t",    #Style number (short)
                    "Marker_t     -> int16_t",    #Marker number (short)
                    "Width_t      -> int16_t",    #Line width (short)
                    "Color_t      -> int16_t",    #Color number (short)
                    "SCoord_t     -> int16_t",    #Screen coordinates (short)
                    "Coord_t      -> double",     #Pad world coordinates (double)
                    "Angle_t      -> float",      #Graphics angle (float)
                    "Size_t       -> float",       #Attribute size (float)
                    #pointer versions
                    "UChar_t *      -> uint8_t *",
                    "Char_t *       -> char *",
                    "UShort_t *     -> uint16_t *",
                    "Short_t *      -> int16_t *",
                    "UInt_t *       -> uint32_t *",
                    "Int_t *        -> int32_t *",
                    "Seek_t *       -> int *",
                    "ULong_t *      -> uint64_t *",
                    "Long_t *       -> int64_t *",
                    "Float_t *      -> float *",
                    "Double_t *     -> double *",
                    "Bool_t *       -> bool *",
                    "Byte_t *       -> uint8_t *",
                    "Version_t *    -> int16_t *",
                    "Ssiz_t *       -> int *",
                    "Real_t *       -> float *",
                    "ULong64_t *    -> uint64_t *",
                    "Long64_t *     -> int64_t *",
                    "ULongptr_t *   -> uint64_t",
                    "Longptr_t *    -> int64_t *",
                    "Axis_t *       -> double *",
                    "Stat_t *       -> double *",
                    "Font_t *       -> int16_t *",
                    "Style_t *      -> int16_t *",
                    "Marker_t *     -> int16_t *",
                    "Width_t *      -> int16_t *",
                    "Color_t *      -> int16_t *",
                    "SCoord_t *     -> int16_t *",
                    "Coord_t *      -> double *",
                    "Angle_t *      -> float *",
                    "Size_t *       -> float *",
                    #reference versions
                    "UChar_t &      -> uint8_t &",
                    "Char_t &       -> int8_t &",
                    "UShort_t &     -> uint16_t &",
                    "Short_t &      -> int16_t &",
                    "UInt_t &       -> uint32_t &",
                    "Int_t &        -> int32_t &",
                    "Seek_t &       -> int &",
                    "ULong_t &      -> uint64_t &",
                    "Long_t &       -> int64_t &",
                    "Float_t &      -> float &",
                    "Double_t &     -> double &",
                    "Bool_t &       -> bool &",
                    "Byte_t &       -> uint8_t &",
                    "Version_t &    -> int16_t &",
                    "Ssiz_t &       -> int &",
                    "Real_t &       -> float &",
                    "ULong64_t &    -> uint64_t &",
                    "Long64_t &     -> int64_t &",
                    "ULongptr_t &   -> uint64_t &",
                    "Longptr_t &    -> int64_t &",
                    "Axis_t &       -> double &",
                    "Stat_t &       -> double &",
                    "Font_t &       -> int16_t &",
                    "Style_t &      -> int16_t &",
                    "Marker_t &     -> int16_t &",
                    "Width_t &      -> int16_t &",
                    "Color_t &      -> int16_t &",
                    "SCoord_t &     -> int16_t &",
                    "Coord_t &      -> double &",
                    "Angle_t &      -> float &",
                    "Size_t &       -> float &",
                   ]
