language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix: 
    #- JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - which julia
  - julia -e "println(JULIA_HOME)"
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/jpata/ROOT.jl.git"); Pkg.build("ROOT")'
  - julia test/wrapper.jl
