language: julia
julia:
  - nightly
os:
  - linux
  - osx
env:
  - ROOT=6.04
notifications:
  email: false

#root install in travis stolen from https://github.com/rootpy/rootpy/blob/master/.travis.yml
#uses conda to install root with the recipes of https://github.com/remenska/root-conda-recipes
#
install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda install -c msarahan libgcc # https://github.com/conda/conda-recipes/issues/558
  - conda config --add channels http://conda.anaconda.org/NLeSC
  - conda config --set show_channel_urls yes
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then conda install -c msarahan libgcc; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then conda install -c msarahan libgcc; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then conda create -q -n testenv python=2.7 root=${ROOT} libgcc=5.2.0; rm /home/travis/miniconda/envs/testenv/lib/libstdc++.so.6; rm /home/travis/miniconda/envs/testenv/lib/libstdc++.so; ln -s /home/travis/miniconda/envs/testenv/lib/libstdc++.so.6.0.21 /home/travis/miniconda/envs/testenv/lib/libstdc++.so.6; ln -s /home/travis/miniconda/envs/testenv/lib/libstdc++.so.6.0.21 /home/travis/miniconda/envs/testenv/lib/libstdc++.so; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then conda create -q -n testenv python=2.7 root=${ROOT}; fi
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - bash ci/test.sh
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ROOT"); Pkg.test("ROOT")'
